# Generated by Django 5.2.4 on 2025-07-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('velocidad', models.FloatField()),
                ('tiempo_espera', models.FloatField()),
                ('direccion', models.CharField(choices=[('N', 'Norte a Sur'), ('S', 'Sur a Norte')], max_length=1)),
                ('en_puente', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
