# Generated by Django 5.2.4 on 2025-07-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('N', 'Norte a Sur'), ('S', 'Sur a Norte')], max_length=1)),
                ('velocidad', models.FloatField()),
                ('turno', models.PositiveIntegerField()),
                ('tiempo_cruce', models.FloatField()),
                ('tiempo_espera', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
